os: linux

dist: trusty

sudo: required

language: cpp

compiler: gcc

addons:

  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-7
      - g++-7
      - swig
      - libxml2-dev
      - python-dev
      - python-sphinx
      - doxygen
      - lcov

cache:


notifications:
  email: false

env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools

  - chmod +x SpeectLib/install.sh
  - ./SpeectLib/install.sh

install:
  - sudo apt-get install -qq g++-5
  - sudo apt-get install libcppunit-dev
  - ccmake . 
  - make
